name: CI

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - name: Firebase Deploy
      uses: jakejarvis/firebase-deploy-action@v0.1.0
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
